#!/usr/bin/env python3
"""Historical placeholder; interpolation is intentionally disabled."""

raise SystemExit(
    "2019 men's result values must not be generated by interpolation. "
    "Use transcripts/2019-男子.json and retain unreadable cells as unknown."
)
